---
title: case:switch:sanity:insanity
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: 'Travel, VR, Drones

'
baseurl: ''
url: https://izhang.github.io
github_username: iZhang
permalink: pretty
markdown: kramdown
theme: minima
gems:
- jekyll-feed
- jemoji
exclude:
- Gemfile
- Gemfile.lock
- package.json
- node_modules
- gulpfile.js
